### ISSUE TITLE
jq-like DSL?

### ISSUE THREAD

**Issue by cyberhuman** [mgdm/htmlq#29]
I decided to try htmlq since I have quite some positive experience with jq. But the first practical task I tried to implement doesn't seem possible with htmlq because of limitations of CSS. Specifically, I need to extract a list of elements matching some CSS selector, that also have some child matching some other selector. Example:
```
# select elements that have the data-attr1 attribute
htmlq -f input.html '[data-attr1]'

# select <span> elements
htmlq -f input.html 'span'

# select <span> elements that are descentants of elements with the data-attr1 attribute
htmlq -f input.html '[data-attr1] span'

# select elements that have the data-attr1 attribute and some <span> descendants
# impossible
```
I imagine it would be possible with some DSL, for example (very crude):
```
css("[data-attr1]") | select(isempty(css("span")) | not)
```

**Comment by davidscotson** [comment]
Version 4 of CSS has something for this, and generally it would be good to follow the future standards when adding features:
 
https://developer.mozilla.org/en-US/docs/Web/CSS/:has
https://css-tricks.com/did-you-know-about-the-has-css-selector/

'[data-attr1]:has(span)' is how your example would be expressed I think.

Worth noting that this particular item has been slow to implement in browsers due to fears of performance issues, but that might not matter for this usage.

**Comment by mgdm** [comment]
If that syntax ends up being implemented in html5ever and kuchiki (the underlying libraries that htmlq uses), we should get it essentially for free. I'll keep an eye out for it.
