### ISSUE TITLE
Does htmlq support very large XML?

### ISSUE THREAD

**Issue by she3o** [mgdm/htmlq#30]
Hi

I downloaded htmlq to process a large XML database (1.4GB, [link](https://go.drugbank.com/releases/5-1-8/downloads/all-full-database)) before data analysis.

when I run  `cat 'full database' | htmlq 'drug'`the command would run for 10 seconds before htmlq runs out of memory. 

Is that behaviour expected or is this a memory bug?

**Comment by ralyodio** [comment]
I'm wondering the same. Need to parse xml as well as html

**Comment by mgdm** [comment]
I don't really expect this tool to behave all that well with that size of XML input. It specifically uses an HTML5 parser to implement all of the rules in that spec, which diverged quite a bit from that of XML. Also, the CSS selector syntax is pretty closely tied to HTML rather than XML. I'd probably recommend you use something like XMLStarlet for that purpose (it's what I use in those cases).
